### ISSUE TITLE
RakuDist test fails 

### ISSUE THREAD

**Issue by melezhik** [alabamenhu/DateTimeTimezones#3]
```
19:06:22 11/02/2020 [bash: zef install DateTime::Timezones] ===> Testing: DateTime::Timezones:ver<0.3.3>:auth<github:alabamenhu>
19:06:41 11/02/2020 [bash: zef install DateTime::Timezones] ===> Testing [OK] for DateTime::Timezones:ver<0.3.3>:auth<github:alabamenhu>
19:06:41 11/02/2020 [bash: zef install DateTime::Timezones] ===> Installing: DateTime::Timezones:ver<0.3.3>:auth<github:alabamenhu>
19:06:42 11/02/2020 [bash: zef install DateTime::Timezones] ===> Install [FAIL] for DateTime::Timezones:ver<0.3.3>:auth<github:alabamenhu>: Not enough positional arguments; needed at least 2
19:06:42 11/02/2020 [bash: zef install DateTime::Timezones] stderr: Not enough positional arguments; needed at least 2
19:06:42 11/02/2020 [bash: zef install DateTime::Timezones] task exit status: 1
19:06:42 11/02/2020 [bash: zef install DateTime::Timezones] task bash: zef install DateTime::Timezones FAILED
Error: non zero exit code: 1: OCI runtime error

```

Full log is available here - http://rakudist.raku.org/sparky/report/debian/859

HTH

**Comment by alabamenhu** [comment]
Hmm, this is an interesting one — it seems to be passing the tests, so I'm not sure what's causing an install fail.  

Did you have a previous version of `DateTime::TimeZones` installed?

**Comment by alabamenhu** [comment]
Also, can you try using `zef install DateTime::Timezones --verbose` (or is this already the verbose output?)

**Comment by melezhik** [comment]
Sorry, for the noise, it's probably some sporadic issue with Rakudist/zef, succeeded after second run - http://rakudist.raku.org/sparky/report/debian/862

**Comment by melezhik** [comment]
cc @ugexe

**Comment by alabamenhu** [comment]
@melezhik  No problem, I actually was just about to report back I saw it run successfully on 2020.10 and 2020.07.  This was the first time I did a fully hands off database upgrade, so when the report came in initially, I assumed it could have been me.

I'll close it accordingly, but if ugexe sees somewhere I've messed up (entirely possible) I'll reopen and fix accordingly.  Thanks for giving me a heads up in any case!

**Comment by ugexe** [comment]
Looks like its failing during precomp (which happens inside of `CompUnit::Repository::Installation.install(...)`), so its an issue outside of zef or rakudist (I doubt user code is ever responsible for throwing [that error](https://github.com/MoarVM/MoarVM/blob/590bac47edc30d16acb8665dbb6b0ec0dfbd7574/src/core/args.c#L232))

**Comment by melezhik** [comment]
thanks @ugexe , I'm just curious why it could be? worth to highlight it to raku devs?
